# Generated by Django 3.2.5 on 2021-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('documento', models.IntegerField(max_length=10)),
                ('pasaporte', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='estudios_formales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=20)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.BooleanField()),
                ('titulo', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=30)),
                ('puesto', models.CharField(max_length=30)),
                ('ingreso', models.DateField()),
                ('egreso', models.DateField()),
                ('descripción', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hobbis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=200)),
            ],
        ),
    ]
