# Generated by Django 3.2.5 on 2021-07-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datos',
            new_name='dato',
        ),
        migrations.RenameModel(
            old_name='estudios_formales',
            new_name='estudios_formale',
        ),
        migrations.RenameModel(
            old_name='hobbis',
            new_name='hobbi',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='skill',
        ),
    ]
