# Generated by Django 3.2.5 on 2021-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20210722_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios_formale',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='descripción',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
