# Generated by Django 3.2.5 on 2021-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_auto_20210722_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='documento',
            field=models.IntegerField(),
        ),
    ]
