# Generated by Django 3.2.5 on 2021-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_alter_dato_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='puesto',
            field=models.CharField(max_length=60),
        ),
    ]
